// ==========================================
// ARCANE DEPTHS – Skill Tree Data (v1.0)
// ==========================================
// Pure data: no DOM, no persistence, no game logic.
// Two categories: 'combat' and 'passive'
// Nodes reference each other by ID.
// Prerequisites: ALL of `prereq` must be owned.
// PrerequisiteAny: at least ONE of `prereqAny` must be owned.
// Exclusions: if you own this node, all nodes listed in `excl` are permanently blocked.
//
// Effects are flat multiplier/bonus objects consumed by SkillTree.getModifiers().
// Negative values on pct fields = reduction (e.g. fireRatePct: -0.02 = 2% faster).
//
// Positions (x,y) are virtual canvas coords used by the UI renderer.
// Virtual canvas size: ~1400 x 1100 per category.
// ==========================================

(function () {

    // ── COST FORMULA ──────────────────────────────────────────────
    // Tier 0 → 2 | Tier 1 → 4 | Tier 2 → 8 | Tier 3 → 15 | Tier 4 → 25 | Tier 5 → 45
    const TIER_COST = [2, 4, 8, 15, 25, 45];

    // ── COMBAT NODES ──────────────────────────────────────────────

    const SkillTreeData = {
        version: '1.0',

        // cost per tier
        tierCosts: [2, 4, 8, 15, 25, 45],

        categories: ['combat', 'passive'],

        nodes: [
            // ══════════════════════════════════════════
            //  COMBAT TREE
            // ══════════════════════════════════════════
            // Tier 0 – root
            {
                id: 'c_root', category: 'combat', tier: 0,
                x: 1900, y: 60,
                prereq: [], prereqAny: [], excl: [],
                icon: '⚔️',
                nameKey: 'sk_c_root', descKey: 'sk_c_root_d',
                effects: { damagePct: 0.01, projSpeedPct: 0.01 },
            },

            // Tier 1 – two parallel paths
            {
                id: 'c1_power', category: 'combat', tier: 1,
                x: 1820, y: 185,
                prereq: ['c_root'], prereqAny: [], excl: [],
                icon: '💥',
                nameKey: 'sk_c1_power', descKey: 'sk_c1_power_d',
                effects: { damagePct: 0.02 },
            },
            {
                id: 'c1_speed', category: 'combat', tier: 1,
                x: 1900, y: 185,
                prereq: ['c_root'], prereqAny: [], excl: [],
                icon: '⚡',
                nameKey: 'sk_c1_speed', descKey: 'sk_c1_speed_d',
                effects: { fireRatePct: -0.02 },
            },

            // Tier 2 – exclusive pairs per branch
            {
                id: 'c2_blade', category: 'combat', tier: 2,
                x: 1300, y: 320,
                prereq: ['c1_power'], prereqAny: [], excl: ['c2_arcane'],
                icon: '🗡️',
                nameKey: 'sk_c2_blade', descKey: 'sk_c2_blade_d',
                effects: { damagePct: 0.03 },
            },
            {
                id: 'c2_arcane', category: 'combat', tier: 2,
                x: 1380, y: 320,
                prereq: ['c1_power'], prereqAny: [], excl: ['c2_blade'],
                icon: '🔮',
                nameKey: 'sk_c2_arcane', descKey: 'sk_c2_arcane_d',
                effects: { critChancePct: 0.02, projSpeedPct: 0.02 },
            },
            {
                id: 'c2_burst', category: 'combat', tier: 2,
                x: 1460, y: 320,
                prereq: ['c1_speed'], prereqAny: [], excl: ['c2_flow'],
                icon: '🔫',
                nameKey: 'sk_c2_burst', descKey: 'sk_c2_burst_d',
                effects: { fireRatePct: -0.03 },
            },
            {
                id: 'c2_flow', category: 'combat', tier: 2,
                x: 1540, y: 320,
                prereq: ['c1_speed'], prereqAny: [], excl: ['c2_burst'],
                icon: '🌀',
                nameKey: 'sk_c2_flow', descKey: 'sk_c2_flow_d',
                effects: { fireRatePct: -0.02, manaCostPct: -0.05 },
            },

            // Tier 3 – 8 nodes, 4 exclusive pairs
            {
                id: 'c3_heavy', category: 'combat', tier: 3,
                x: 1300, y: 480,
                prereq: ['c2_blade'], prereqAny: [], excl: ['c3_keen'],
                icon: '🔨',
                nameKey: 'sk_c3_heavy', descKey: 'sk_c3_heavy_d',
                effects: { damagePct: 0.04, fireRatePct: 0.01 },
            },
            {
                id: 'c3_keen', category: 'combat', tier: 3,
                x: 1380, y: 480,
                prereq: ['c2_blade'], prereqAny: [], excl: ['c3_heavy'],
                icon: '🔪',
                nameKey: 'sk_c3_keen', descKey: 'sk_c3_keen_d',
                effects: { damagePct: 0.02, projRangePct: 0.04 },
            },
            {
                id: 'c3_crit', category: 'combat', tier: 3,
                x: 1460, y: 480,
                prereq: ['c2_arcane'], prereqAny: [], excl: ['c3_chain'],
                icon: '🎯',
                nameKey: 'sk_c3_crit', descKey: 'sk_c3_crit_d',
                effects: { critChancePct: 0.03 },
            },
            {
                id: 'c3_chain', category: 'combat', tier: 3,
                x: 1540, y: 480,
                prereq: ['c2_arcane'], prereqAny: [], excl: ['c3_crit'],
                icon: '⛓️',
                nameKey: 'sk_c3_chain', descKey: 'sk_c3_chain_d',
                effects: { chainHitPct: 0.02 },
            },
            {
                id: 'c3_rapid', category: 'combat', tier: 3,
                x: 1620, y: 480,
                prereq: ['c2_burst'], prereqAny: [], excl: ['c3_swift'],
                icon: '🌪️',
                nameKey: 'sk_c3_rapid', descKey: 'sk_c3_rapid_d',
                effects: { fireRatePct: -0.04 },
            },
            {
                id: 'c3_swift', category: 'combat', tier: 3,
                x: 1700, y: 480,
                prereq: ['c2_burst'], prereqAny: [], excl: ['c3_rapid'],
                icon: '💨',
                nameKey: 'sk_c3_swift', descKey: 'sk_c3_swift_d',
                effects: { fireRatePct: -0.03, moveSpeedPct: 0.02 },
            },
            {
                id: 'c3_mana', category: 'combat', tier: 3,
                x: 1780, y: 480,
                prereq: ['c2_flow'], prereqAny: [], excl: ['c3_focus'],
                icon: '🔷',
                nameKey: 'sk_c3_mana', descKey: 'sk_c3_mana_d',
                effects: { manaCostPct: -0.08 },
            },
            {
                id: 'c3_focus', category: 'combat', tier: 3,
                x: 1860, y: 480,
                prereq: ['c2_flow'], prereqAny: [], excl: ['c3_mana'],
                icon: '🔵',
                nameKey: 'sk_c3_focus', descKey: 'sk_c3_focus_d',
                effects: { manaCostPct: -0.05, damagePct: 0.02 },
            },

            // Tier 4 – 16 nodes, 8 exclusive pairs
            // Spread evenly: x from 50 to 1350, step ≈ 87
            {
                id: 'c4_crusher', category: 'combat', tier: 4,
                x: 1300, y: 700,
                prereq: ['c3_heavy'], prereqAny: [], excl: ['c4_tank'],
                icon: '💪',
                nameKey: 'sk_c4_crusher', descKey: 'sk_c4_crusher_d',
                effects: { damagePct: 0.05, maxHpFlat: 5 },
            },
            {
                id: 'c4_tank', category: 'combat', tier: 4,
                x: 1380, y: 700,
                prereq: ['c3_heavy'], prereqAny: [], excl: ['c4_crusher'],
                icon: '🛡️',
                nameKey: 'sk_c4_tank', descKey: 'sk_c4_tank_d',
                effects: { damagePct: 0.03, dmgReductionPct: 0.03 },
            },
            {
                id: 'c4_sniper', category: 'combat', tier: 4,
                x: 1460, y: 700,
                prereq: ['c3_keen'], prereqAny: [], excl: ['c4_spread'],
                icon: '🔭',
                nameKey: 'sk_c4_sniper', descKey: 'sk_c4_sniper_d',
                effects: { projRangePct: 0.05, damagePct: 0.02 },
            },
            {
                id: 'c4_spread', category: 'combat', tier: 4,
                x: 1540, y: 700,
                prereq: ['c3_keen'], prereqAny: [], excl: ['c4_sniper'],
                icon: '🔴',
                nameKey: 'sk_c4_spread', descKey: 'sk_c4_spread_d',
                effects: { projSpeedPct: 0.04, damagePct: 0.02 },
            },
            {
                id: 'c4_deathblow', category: 'combat', tier: 4,
                x: 1620, y: 700,
                prereq: ['c3_crit'], prereqAny: [], excl: ['c4_vampiric'],
                icon: '💀',
                nameKey: 'sk_c4_deathblow', descKey: 'sk_c4_deathblow_d',
                effects: { critChancePct: 0.04, critDmgPct: 0.10 },
            },
            {
                id: 'c4_vampiric', category: 'combat', tier: 4,
                x: 1700, y: 700,
                prereq: ['c3_crit'], prereqAny: [], excl: ['c4_deathblow'],
                icon: '🩸',
                nameKey: 'sk_c4_vampiric', descKey: 'sk_c4_vampiric_d',
                effects: { critChancePct: 0.02, lifeStealPct: 0.005 },
            },
            {
                id: 'c4_storm', category: 'combat', tier: 4,
                x: 1780, y: 700,
                prereq: ['c3_chain'], prereqAny: [], excl: ['c4_nova'],
                icon: '⛈️',
                nameKey: 'sk_c4_storm', descKey: 'sk_c4_storm_d',
                effects: { chainHitPct: 0.02, damagePct: 0.01 },
            },
            {
                id: 'c4_nova', category: 'combat', tier: 4,
                x: 1860, y: 700,
                prereq: ['c3_chain'], prereqAny: [], excl: ['c4_storm'],
                icon: '✨',
                nameKey: 'sk_c4_nova', descKey: 'sk_c4_nova_d',
                effects: { projSpeedPct: 0.03, damagePct: 0.01 },
            },
            {
                id: 'c4_machinegun', category: 'combat', tier: 4,
                x: 1940, y: 700,
                prereq: ['c3_rapid'], prereqAny: [], excl: ['c4_dual'],
                icon: '🔧',
                nameKey: 'sk_c4_machinegun', descKey: 'sk_c4_machinegun_d',
                effects: { fireRatePct: -0.05, damagePct: -0.01 },
            },
            {
                id: 'c4_dual', category: 'combat', tier: 4,
                x: 2020, y: 700,
                prereq: ['c3_rapid'], prereqAny: [], excl: ['c4_machinegun'],
                icon: '🔄',
                nameKey: 'sk_c4_dual', descKey: 'sk_c4_dual_d',
                effects: { doubleShotChancePct: 0.01, fireRatePct: -0.02 },
            },
            {
                id: 'c4_dancer', category: 'combat', tier: 4,
                x: 2100, y: 700,
                prereq: ['c3_swift'], prereqAny: [], excl: ['c4_agile'],
                icon: '🩺',
                nameKey: 'sk_c4_dancer', descKey: 'sk_c4_dancer_d',
                effects: { moveSpeedPct: 0.03, damagePct: 0.01 },
            },
            {
                id: 'c4_agile', category: 'combat', tier: 4,
                x: 2180, y: 700,
                prereq: ['c3_swift'], prereqAny: [], excl: ['c4_dancer'],
                icon: '🏃',
                nameKey: 'sk_c4_agile', descKey: 'sk_c4_agile_d',
                effects: { dashCooldownPct: -0.05, moveSpeedPct: 0.02 },
            },
            {
                id: 'c4_reservoir', category: 'combat', tier: 4,
                x: 2260, y: 700,
                prereq: ['c3_mana'], prereqAny: [], excl: ['c4_efficient'],
                icon: '💧',
                nameKey: 'sk_c4_reservoir', descKey: 'sk_c4_reservoir_d',
                effects: { manaCostPct: -0.10, maxManaFlat: 5 },
            },
            {
                id: 'c4_efficient', category: 'combat', tier: 4,
                x: 2340, y: 700,
                prereq: ['c3_mana'], prereqAny: [], excl: ['c4_reservoir'],
                icon: '⚙️',
                nameKey: 'sk_c4_efficient', descKey: 'sk_c4_efficient_d',
                effects: { manaCostPct: -0.08, damagePct: 0.02 },
            },
            {
                id: 'c4_overdrive', category: 'combat', tier: 4,
                x: 2420, y: 700,
                prereq: ['c3_focus'], prereqAny: [], excl: ['c4_balance_c'],
                icon: '🌋',
                nameKey: 'sk_c4_overdrive', descKey: 'sk_c4_overdrive_d',
                effects: { damagePct: 0.04, manaCostPct: -0.02 },
            },
            {
                id: 'c4_balance_c', category: 'combat', tier: 4,
                x: 2500, y: 700,
                prereq: ['c3_focus'], prereqAny: [], excl: ['c4_overdrive'],
                icon: '☯️',
                nameKey: 'sk_c4_balance_c', descKey: 'sk_c4_balance_c_d',
                effects: { damagePct: 0.02, manaCostPct: -0.03, critChancePct: 0.01 },
            },

            // Tier 5 – 4 ultimate nodes, 2 exclusive pairs
            {
                id: 'c5_warlord', category: 'combat', tier: 5,
                x: 1300, y: 960,
                prereq: [], prereqAny: ['c4_crusher', 'c4_tank', 'c4_sniper', 'c4_spread', 'c4_deathblow', 'c4_vampiric', 'c4_storm', 'c4_nova'],
                excl: ['c5_assassin'],
                icon: '⚜️',
                nameKey: 'sk_c5_warlord', descKey: 'sk_c5_warlord_d',
                effects: { damagePct: 0.05, maxHpFlat: 8, critChancePct: 0.01 },
            },
            {
                id: 'c5_assassin', category: 'combat', tier: 5,
                x: 1380, y: 960,
                prereq: [], prereqAny: ['c4_crusher', 'c4_tank', 'c4_sniper', 'c4_spread', 'c4_deathblow', 'c4_vampiric', 'c4_storm', 'c4_nova'],
                excl: ['c5_warlord'],
                icon: '🥷',
                nameKey: 'sk_c5_assassin', descKey: 'sk_c5_assassin_d',
                effects: { damagePct: 0.06, critChancePct: 0.03 },
            },
            {
                id: 'c5_tempest', category: 'combat', tier: 5,
                x: 1460, y: 960,
                prereq: [], prereqAny: ['c4_machinegun', 'c4_dual', 'c4_dancer', 'c4_agile', 'c4_reservoir', 'c4_efficient', 'c4_overdrive', 'c4_balance_c'],
                excl: ['c5_torrent'],
                icon: '🌩️',
                nameKey: 'sk_c5_tempest', descKey: 'sk_c5_tempest_d',
                effects: { fireRatePct: -0.05, damagePct: 0.02 },
            },
            {
                id: 'c5_torrent', category: 'combat', tier: 5,
                x: 1540, y: 960,
                prereq: [], prereqAny: ['c4_machinegun', 'c4_dual', 'c4_dancer', 'c4_agile', 'c4_reservoir', 'c4_efficient', 'c4_overdrive', 'c4_balance_c'],
                excl: ['c5_tempest'],
                icon: '💫',
                nameKey: 'sk_c5_torrent', descKey: 'sk_c5_torrent_d',
                effects: { projSpeedPct: 0.04, fireRatePct: -0.03, projRangePct: 0.03 },
            },

            // ══════════════════════════════════════════
            //  PASSIVE TREE
            // ══════════════════════════════════════════
            // Tier 0 – root
            {
                id: 'p_root', category: 'passive', tier: 0,
                x: 1900, y: 60,
                prereq: [], prereqAny: [], excl: [],
                icon: '💚',
                nameKey: 'sk_p_root', descKey: 'sk_p_root_d',
                effects: { maxHpFlat: 5, luckPct: 0.01 },
            },

            // Tier 1
            {
                id: 'p1_vitality', category: 'passive', tier: 1,
                x: 1860, y: 185,
                prereq: ['p_root'], prereqAny: [], excl: [],
                icon: '❤️',
                nameKey: 'sk_p1_vitality', descKey: 'sk_p1_vitality_d',
                effects: { maxHpFlat: 5 },
            },
            {
                id: 'p1_fortune', category: 'passive', tier: 1,
                x: 1940, y: 185,
                prereq: ['p_root'], prereqAny: [], excl: [],
                icon: '🍀',
                nameKey: 'sk_p1_fortune', descKey: 'sk_p1_fortune_d',
                effects: { luckPct: 0.02 },
            },

            // Tier 2
            {
                id: 'p2_regen', category: 'passive', tier: 2,
                x: 1300, y: 320,
                prereq: ['p1_vitality'], prereqAny: [], excl: ['p2_armor'],
                icon: '💊',
                nameKey: 'sk_p2_regen', descKey: 'sk_p2_regen_d',
                effects: { hpRegenPerSec: 0.3 },
            },
            {
                id: 'p2_armor', category: 'passive', tier: 2,
                x: 1380, y: 320,
                prereq: ['p1_vitality'], prereqAny: [], excl: ['p2_regen'],
                icon: '🪖',
                nameKey: 'sk_p2_armor', descKey: 'sk_p2_armor_d',
                effects: { dmgReductionPct: 0.03, maxHpFlat: 3 },
            },
            {
                id: 'p2_gold', category: 'passive', tier: 2,
                x: 1460, y: 320,
                prereq: ['p1_fortune'], prereqAny: [], excl: ['p2_drops'],
                icon: '💰',
                nameKey: 'sk_p2_gold', descKey: 'sk_p2_gold_d',
                effects: { goldPct: 0.05 },
            },
            {
                id: 'p2_drops', category: 'passive', tier: 2,
                x: 1540, y: 320,
                prereq: ['p1_fortune'], prereqAny: [], excl: ['p2_gold'],
                icon: '🔍',
                nameKey: 'sk_p2_drops', descKey: 'sk_p2_drops_d',
                effects: { luckPct: 0.02, shopSlotsBonus: 0 }, // itemDropRate via luck
            },

            // Tier 3
            {
                id: 'p3_resilient', category: 'passive', tier: 3,
                x: 1300, y: 480,
                prereq: ['p2_regen'], prereqAny: [], excl: ['p3_lifesteal'],
                icon: '💪',
                nameKey: 'sk_p3_resilient', descKey: 'sk_p3_resilient_d',
                effects: { maxHpFlat: 5, hpRegenPerSec: 0.2 },
            },
            {
                id: 'p3_lifesteal', category: 'passive', tier: 3,
                x: 1380, y: 480,
                prereq: ['p2_regen'], prereqAny: [], excl: ['p3_resilient'],
                icon: '🩸',
                nameKey: 'sk_p3_lifesteal', descKey: 'sk_p3_lifesteal_d',
                effects: { lifeStealPct: 0.005 },
            },
            {
                id: 'p3_fortress', category: 'passive', tier: 3,
                x: 1460, y: 480,
                prereq: ['p2_armor'], prereqAny: [], excl: ['p3_spikes'],
                icon: '🏰',
                nameKey: 'sk_p3_fortress', descKey: 'sk_p3_fortress_d',
                effects: { dmgReductionPct: 0.05, maxHpFlat: 5 },
            },
            {
                id: 'p3_spikes', category: 'passive', tier: 3,
                x: 1540, y: 480,
                prereq: ['p2_armor'], prereqAny: [], excl: ['p3_fortress'],
                icon: '🦔',
                nameKey: 'sk_p3_spikes', descKey: 'sk_p3_spikes_d',
                effects: { reflectDmgPct: 0.01 },
            },
            {
                id: 'p3_merchant', category: 'passive', tier: 3,
                x: 1620, y: 480,
                prereq: ['p2_gold'], prereqAny: [], excl: ['p3_hoarder'],
                icon: '🏪',
                nameKey: 'sk_p3_merchant', descKey: 'sk_p3_merchant_d',
                effects: { goldPct: 0.08, shopRerollsBonus: 1 },
            },
            {
                id: 'p3_hoarder', category: 'passive', tier: 3,
                x: 1700, y: 480,
                prereq: ['p2_gold'], prereqAny: [], excl: ['p3_merchant'],
                icon: '💎',
                nameKey: 'sk_p3_hoarder', descKey: 'sk_p3_hoarder_d',
                effects: { goldPct: 0.05, startGoldFlat: 50 },
            },
            {
                id: 'p3_scavenger', category: 'passive', tier: 3,
                x: 1780, y: 480,
                prereq: ['p2_drops'], prereqAny: [], excl: ['p3_lucky'],
                icon: '🦅',
                nameKey: 'sk_p3_scavenger', descKey: 'sk_p3_scavenger_d',
                effects: { luckPct: 0.03, shopSlotsBonus: 1 },
            },
            {
                id: 'p3_lucky', category: 'passive', tier: 3,
                x: 1860, y: 480,
                prereq: ['p2_drops'], prereqAny: [], excl: ['p3_scavenger'],
                icon: '⭐',
                nameKey: 'sk_p3_lucky', descKey: 'sk_p3_lucky_d',
                effects: { luckPct: 0.04, shopRerollsBonus: 1 },
            },

            // Tier 4 – 16 nodes, 8 pairs
            {
                id: 'p4_ironwill', category: 'passive', tier: 4,
                x: 1300, y: 700,
                prereq: ['p3_resilient'], prereqAny: [], excl: ['p4_phoenix'],
                icon: '🪨',
                nameKey: 'sk_p4_ironwill', descKey: 'sk_p4_ironwill_d',
                effects: { maxHpFlat: 8, hpRegenPerSec: 0.5 },
            },
            {
                id: 'p4_phoenix', category: 'passive', tier: 4,
                x: 1380, y: 700,
                prereq: ['p3_resilient'], prereqAny: [], excl: ['p4_ironwill'],
                icon: '🔥',
                nameKey: 'sk_p4_phoenix', descKey: 'sk_p4_phoenix_d',
                effects: { maxHpFlat: 3, phoenixPassive: true },
            },
            {
                id: 'p4_vampire', category: 'passive', tier: 4,
                x: 1460, y: 700,
                prereq: ['p3_lifesteal'], prereqAny: [], excl: ['p4_bloodrush'],
                icon: '🧛',
                nameKey: 'sk_p4_vampire', descKey: 'sk_p4_vampire_d',
                effects: { lifeStealPct: 0.01, maxHpFlat: 3 },
            },
            {
                id: 'p4_bloodrush', category: 'passive', tier: 4,
                x: 1540, y: 700,
                prereq: ['p3_lifesteal'], prereqAny: [], excl: ['p4_vampire'],
                icon: '🔴',
                nameKey: 'sk_p4_bloodrush', descKey: 'sk_p4_bloodrush_d',
                effects: { lifeStealPct: 0.005, damagePct: 0.02 },
            },
            {
                id: 'p4_bulwark', category: 'passive', tier: 4,
                x: 1620, y: 700,
                prereq: ['p3_fortress'], prereqAny: [], excl: ['p4_guardian'],
                icon: '⛩️',
                nameKey: 'sk_p4_bulwark', descKey: 'sk_p4_bulwark_d',
                effects: { dmgReductionPct: 0.07 },
            },
            {
                id: 'p4_guardian', category: 'passive', tier: 4,
                x: 1700, y: 700,
                prereq: ['p3_fortress'], prereqAny: [], excl: ['p4_bulwark'],
                icon: '🏛️',
                nameKey: 'sk_p4_guardian', descKey: 'sk_p4_guardian_d',
                effects: { dmgReductionPct: 0.05, maxHpFlat: 5 },
            },
            {
                id: 'p4_thorns', category: 'passive', tier: 4,
                x: 1780, y: 700,
                prereq: ['p3_spikes'], prereqAny: [], excl: ['p4_counter'],
                icon: '🌵',
                nameKey: 'sk_p4_thorns', descKey: 'sk_p4_thorns_d',
                effects: { reflectDmgPct: 0.02, maxHpFlat: 5 },
            },
            {
                id: 'p4_counter', category: 'passive', tier: 4,
                x: 1860, y: 700,
                prereq: ['p3_spikes'], prereqAny: [], excl: ['p4_thorns'],
                icon: '🔁',
                nameKey: 'sk_p4_counter', descKey: 'sk_p4_counter_d',
                effects: { reflectDmgPct: 0.01, critChancePct: 0.01 },
            },
            {
                id: 'p4_broker', category: 'passive', tier: 4,
                x: 1940, y: 700,
                prereq: ['p3_merchant'], prereqAny: [], excl: ['p4_shopmaster'],
                icon: '💼',
                nameKey: 'sk_p4_broker', descKey: 'sk_p4_broker_d',
                effects: { goldPct: 0.10, shopRerollsBonus: 1 },
            },
            {
                id: 'p4_shopmaster', category: 'passive', tier: 4,
                x: 2020, y: 700,
                prereq: ['p3_merchant'], prereqAny: [], excl: ['p4_broker'],
                icon: '🏬',
                nameKey: 'sk_p4_shopmaster', descKey: 'sk_p4_shopmaster_d',
                effects: { goldPct: 0.08, shopSlotsBonus: 1 },
            },
            {
                id: 'p4_miser', category: 'passive', tier: 4,
                x: 2100, y: 700,
                prereq: ['p3_hoarder'], prereqAny: [], excl: ['p4_investor'],
                icon: '🤑',
                nameKey: 'sk_p4_miser', descKey: 'sk_p4_miser_d',
                effects: { goldPct: 0.12, startGoldFlat: 100 },
            },
            {
                id: 'p4_investor', category: 'passive', tier: 4,
                x: 2180, y: 700,
                prereq: ['p3_hoarder'], prereqAny: [], excl: ['p4_miser'],
                icon: '📈',
                nameKey: 'sk_p4_investor', descKey: 'sk_p4_investor_d',
                effects: { goldPct: 0.08, startGoldFlat: 75 },
            },
            {
                id: 'p4_hunter', category: 'passive', tier: 4,
                x: 2260, y: 700,
                prereq: ['p3_scavenger'], prereqAny: [], excl: ['p4_prowler'],
                icon: '🏹',
                nameKey: 'sk_p4_hunter', descKey: 'sk_p4_hunter_d',
                effects: { luckPct: 0.05, dashChargesBonus: 1 },
            },
            {
                id: 'p4_prowler', category: 'passive', tier: 4,
                x: 2340, y: 700,
                prereq: ['p3_scavenger'], prereqAny: [], excl: ['p4_hunter'],
                icon: '🐆',
                nameKey: 'sk_p4_prowler', descKey: 'sk_p4_prowler_d',
                effects: { luckPct: 0.04, moveSpeedPct: 0.03 },
            },
            {
                id: 'p4_fate', category: 'passive', tier: 4,
                x: 2420, y: 700,
                prereq: ['p3_lucky'], prereqAny: [], excl: ['p4_chosen'],
                icon: '🔮',
                nameKey: 'sk_p4_fate', descKey: 'sk_p4_fate_d',
                effects: { luckPct: 0.06, shopSlotsBonus: 1 },
            },
            {
                id: 'p4_chosen', category: 'passive', tier: 4,
                x: 2500, y: 700,
                prereq: ['p3_lucky'], prereqAny: [], excl: ['p4_fate'],
                icon: '🌟',
                nameKey: 'sk_p4_chosen', descKey: 'sk_p4_chosen_d',
                effects: { luckPct: 0.05, critChancePct: 0.03 },
            },

            // Tier 5 – 4 ultimate passive nodes, 2 exclusive pairs
            {
                id: 'p5_ascended', category: 'passive', tier: 5,
                x: 1300, y: 960,
                prereq: [], prereqAny: ['p4_ironwill', 'p4_phoenix', 'p4_vampire', 'p4_bloodrush', 'p4_bulwark', 'p4_guardian', 'p4_thorns', 'p4_counter'],
                excl: ['p5_immortal'],
                icon: '👑',
                nameKey: 'sk_p5_ascended', descKey: 'sk_p5_ascended_d',
                effects: { maxHpFlat: 10, luckPct: 0.03, goldPct: 0.05 },
            },
            {
                id: 'p5_immortal', category: 'passive', tier: 5,
                x: 1380, y: 960,
                prereq: [], prereqAny: ['p4_ironwill', 'p4_phoenix', 'p4_vampire', 'p4_bloodrush', 'p4_bulwark', 'p4_guardian', 'p4_thorns', 'p4_counter'],
                excl: ['p5_ascended'],
                icon: '♾️',
                nameKey: 'sk_p5_immortal', descKey: 'sk_p5_immortal_d',
                effects: { maxHpFlat: 8, hpRegenPerSec: 0.5, dmgReductionPct: 0.03 },
            },
            {
                id: 'p5_destiny', category: 'passive', tier: 5,
                x: 1460, y: 960,
                prereq: [], prereqAny: ['p4_broker', 'p4_shopmaster', 'p4_miser', 'p4_investor', 'p4_hunter', 'p4_prowler', 'p4_fate', 'p4_chosen'],
                excl: ['p5_legend'],
                icon: '🌌',
                nameKey: 'sk_p5_destiny', descKey: 'sk_p5_destiny_d',
                effects: { damagePct: 0.05, luckPct: 0.05, startPotionsFlat: 2 },
            },
            {
                id: 'p5_legend', category: 'passive', tier: 5,
                x: 1540, y: 960,
                prereq: [], prereqAny: ['p4_broker', 'p4_shopmaster', 'p4_miser', 'p4_investor', 'p4_hunter', 'p4_prowler', 'p4_fate', 'p4_chosen'],
                excl: ['p5_destiny'],
                icon: '🏆',
                nameKey: 'sk_p5_legend', descKey: 'sk_p5_legend_d',
                effects: { goldPct: 0.08, shopSlotsBonus: 1, luckPct: 0.05 },
            },

            // ══════════════════════════════════════════
            //  COMBAT TREE – EXTENDED (Tier 1-5 additional branches)
            // ══════════════════════════════════════════

            // --- COMBAT BRANCH: Crit Mastery (from c2_arcane) ---
            { id: 'c3_crit_hunter', category: 'combat', tier: 3, x: 1940, y: 480,
              prereq: ['c2_arcane'], prereqAny: [], excl: ['c3_spell_crusher'],
              icon: '🎯', nameKey: 'sk_c3_crit_hunter', descKey: 'sk_c3_crit_hunter_d',
              effects: { critChancePct: 0.04 } },
            { id: 'c3_spell_crusher', category: 'combat', tier: 3, x: 2020, y: 480,
              prereq: ['c2_arcane'], prereqAny: [], excl: ['c3_crit_hunter'],
              icon: '💫', nameKey: 'sk_c3_spell_crusher', descKey: 'sk_c3_spell_crusher_d',
              effects: { damagePct: 0.04, manaCostPct: 0.05 } },
            { id: 'c4_deadly_focus', category: 'combat', tier: 4, x: 1300, y: 800,
              prereq: ['c3_crit_hunter'], prereqAny: [], excl: ['c4_void_lance'],
              icon: '🔱', nameKey: 'sk_c4_deadly_focus', descKey: 'sk_c4_deadly_focus_d',
              effects: { critDamagePct: 0.15, critChancePct: 0.03 } },
            { id: 'c4_void_lance', category: 'combat', tier: 4, x: 1380, y: 800,
              prereq: ['c3_spell_crusher'], prereqAny: [], excl: ['c4_deadly_focus'],
              icon: '🌑', nameKey: 'sk_c4_void_lance', descKey: 'sk_c4_void_lance_d',
              effects: { damagePct: 0.06, projSpeedPct: 0.05 } },
            { id: 'c5_executioner', category: 'combat', tier: 5, x: 1620, y: 960,
              prereq: [], prereqAny: ['c4_deadly_focus', 'c4_void_lance'], excl: ['c5_obliterate'],
              icon: '💀', nameKey: 'sk_c5_executioner', descKey: 'sk_c5_executioner_d',
              effects: { critChancePct: 0.06, critDamagePct: 0.20 } },
            { id: 'c5_obliterate', category: 'combat', tier: 5, x: 1700, y: 960,
              prereq: [], prereqAny: ['c4_deadly_focus', 'c4_void_lance'], excl: ['c5_executioner'],
              icon: '☄️', nameKey: 'sk_c5_obliterate', descKey: 'sk_c5_obliterate_d',
              effects: { damagePct: 0.10, fireRatePct: -0.03 } },

            // --- COMBAT BRANCH: Speed Mastery (from c2_burst / c2_flow) ---
            { id: 'c3_rapid_caster', category: 'combat', tier: 3, x: 2100, y: 480,
              prereq: ['c2_burst'], prereqAny: [], excl: ['c3_storm_volley'],
              icon: '⚡', nameKey: 'sk_c3_rapid_caster', descKey: 'sk_c3_rapid_caster_d',
              effects: { fireRatePct: -0.04 } },
            { id: 'c3_storm_volley', category: 'combat', tier: 3, x: 2180, y: 480,
              prereq: ['c2_burst'], prereqAny: [], excl: ['c3_rapid_caster'],
              icon: '🌩️', nameKey: 'sk_c3_storm_volley', descKey: 'sk_c3_storm_volley_d',
              effects: { fireRatePct: -0.03, projSpeedPct: 0.04 } },
            { id: 'c3_mana_blade', category: 'combat', tier: 3, x: 2260, y: 480,
              prereq: ['c2_flow'], prereqAny: [], excl: ['c3_ether_stream'],
              icon: '🗡️', nameKey: 'sk_c3_mana_blade', descKey: 'sk_c3_mana_blade_d',
              effects: { damagePct: 0.04, manaCostPct: -0.05 } },
            { id: 'c3_ether_stream', category: 'combat', tier: 3, x: 2340, y: 480,
              prereq: ['c2_flow'], prereqAny: [], excl: ['c3_mana_blade'],
              icon: '🌊', nameKey: 'sk_c3_ether_stream', descKey: 'sk_c3_ether_stream_d',
              effects: { fireRatePct: -0.03, manaCostPct: -0.08 } },
            { id: 'c4_rapid_barrage', category: 'combat', tier: 4, x: 1460, y: 800,
              prereq: ['c3_rapid_caster'], prereqAny: [], excl: ['c4_scatter'],
              icon: '🔥', nameKey: 'sk_c4_rapid_barrage', descKey: 'sk_c4_rapid_barrage_d',
              effects: { fireRatePct: -0.05, damagePct: 0.02 } },
            { id: 'c4_scatter', category: 'combat', tier: 4, x: 1540, y: 800,
              prereq: ['c3_storm_volley'], prereqAny: [], excl: ['c4_rapid_barrage'],
              icon: '💥', nameKey: 'sk_c4_scatter', descKey: 'sk_c4_scatter_d',
              effects: { projSpeedPct: 0.08, damagePct: 0.03 } },
            { id: 'c4_flow_state', category: 'combat', tier: 4, x: 1620, y: 800,
              prereq: ['c3_mana_blade'], prereqAny: [], excl: ['c4_overcharge'],
              icon: '🔄', nameKey: 'sk_c4_flow_state', descKey: 'sk_c4_flow_state_d',
              effects: { fireRatePct: -0.04, manaCostPct: -0.06 } },
            { id: 'c4_overcharge', category: 'combat', tier: 4, x: 1700, y: 800,
              prereq: ['c3_ether_stream'], prereqAny: [], excl: ['c4_flow_state'],
              icon: '⚡', nameKey: 'sk_c4_overcharge', descKey: 'sk_c4_overcharge_d',
              effects: { damagePct: 0.07, manaCostPct: 0.08 } },
            { id: 'c5_hurricane', category: 'combat', tier: 5, x: 1780, y: 960,
              prereq: [], prereqAny: ['c4_rapid_barrage','c4_scatter','c4_flow_state','c4_overcharge'], excl: ['c5_typhoon'],
              icon: '🌪️', nameKey: 'sk_c5_hurricane', descKey: 'sk_c5_hurricane_d',
              effects: { fireRatePct: -0.07, projSpeedPct: 0.06 } },
            { id: 'c5_typhoon', category: 'combat', tier: 5, x: 1860, y: 960,
              prereq: [], prereqAny: ['c4_rapid_barrage','c4_scatter','c4_flow_state','c4_overcharge'], excl: ['c5_hurricane'],
              icon: '🌀', nameKey: 'sk_c5_typhoon', descKey: 'sk_c5_typhoon_d',
              effects: { damagePct: 0.08, manaCostPct: -0.10 } },

            // --- NEW COMBAT BRANCH: Range / Sniper (from c2_blade) ---
            { id: 'c3_long_shot', category: 'combat', tier: 3, x: 2420, y: 480,
              prereq: ['c2_blade'], prereqAny: [], excl: ['c3_penetrator'],
              icon: '🏹', nameKey: 'sk_c3_long_shot', descKey: 'sk_c3_long_shot_d',
              effects: { projRangePct: 0.08, damagePct: 0.02 } },
            { id: 'c3_penetrator', category: 'combat', tier: 3, x: 2500, y: 480,
              prereq: ['c2_blade'], prereqAny: [], excl: ['c3_long_shot'],
              icon: '🔩', nameKey: 'sk_c3_penetrator', descKey: 'sk_c3_penetrator_d',
              effects: { damagePct: 0.05, projRangePct: 0.04 } },
            { id: 'c4_sniper_elite', category: 'combat', tier: 4, x: 1780, y: 800,
              prereq: ['c3_long_shot'], prereqAny: [], excl: ['c4_armor_pierce'],
              icon: '🎯', nameKey: 'sk_c4_sniper_elite', descKey: 'sk_c4_sniper_elite_d',
              effects: { projRangePct: 0.12, critChancePct: 0.03 } },
            { id: 'c4_armor_pierce', category: 'combat', tier: 4, x: 1860, y: 800,
              prereq: ['c3_penetrator'], prereqAny: [], excl: ['c4_sniper_elite'],
              icon: '⚔️', nameKey: 'sk_c4_armor_pierce', descKey: 'sk_c4_armor_pierce_d',
              effects: { damagePct: 0.08, projSpeedPct: 0.05 } },
            { id: 'c5_deadeye', category: 'combat', tier: 5, x: 1940, y: 960,
              prereq: [], prereqAny: ['c4_sniper_elite','c4_armor_pierce'], excl: ['c5_volley_god'],
              icon: '👁️', nameKey: 'sk_c5_deadeye', descKey: 'sk_c5_deadeye_d',
              effects: { critChancePct: 0.08, projRangePct: 0.10 } },
            { id: 'c5_volley_god', category: 'combat', tier: 5, x: 2020, y: 960,
              prereq: [], prereqAny: ['c4_sniper_elite','c4_armor_pierce'], excl: ['c5_deadeye'],
              icon: '🏹', nameKey: 'sk_c5_volley_god', descKey: 'sk_c5_volley_god_d',
              effects: { damagePct: 0.12, fireRatePct: -0.03 } },

            // --- COMBAT BRANCH: Elemental (new mid-tier) ---
            { id: 'c2_fire', category: 'combat', tier: 2, x: 1620, y: 320,
              prereq: ['c_root'], prereqAny: [], excl: [],
              icon: '🔥', nameKey: 'sk_c2_fire', descKey: 'sk_c2_fire_d',
              effects: { damagePct: 0.02, fireRatePct: -0.01 } },
            { id: 'c3_inferno', category: 'combat', tier: 3, x: 1300, y: 580,
              prereq: ['c2_fire'], prereqAny: [], excl: ['c3_frost_bolt'],
              icon: '🌋', nameKey: 'sk_c3_inferno', descKey: 'sk_c3_inferno_d',
              effects: { damagePct: 0.04, critChancePct: 0.02 } },
            { id: 'c3_frost_bolt', category: 'combat', tier: 3, x: 1380, y: 580,
              prereq: ['c2_fire'], prereqAny: [], excl: ['c3_inferno'],
              icon: '❄️', nameKey: 'sk_c3_frost_bolt', descKey: 'sk_c3_frost_bolt_d',
              effects: { projSpeedPct: 0.05, fireRatePct: -0.02 } },
            { id: 'c4_magma', category: 'combat', tier: 4, x: 1940, y: 800,
              prereq: ['c3_inferno'], prereqAny: [], excl: ['c4_blizzard'],
              icon: '🌊', nameKey: 'sk_c4_magma', descKey: 'sk_c4_magma_d',
              effects: { damagePct: 0.06, critDamagePct: 0.10 } },
            { id: 'c4_blizzard', category: 'combat', tier: 4, x: 2020, y: 800,
              prereq: ['c3_frost_bolt'], prereqAny: [], excl: ['c4_magma'],
              icon: '🌨️', nameKey: 'sk_c4_blizzard', descKey: 'sk_c4_blizzard_d',
              effects: { projSpeedPct: 0.08, damagePct: 0.04 } },
            { id: 'c5_armageddon', category: 'combat', tier: 5, x: 2100, y: 960,
              prereq: [], prereqAny: ['c4_magma','c4_blizzard'], excl: ['c5_ice_age'],
              icon: '☄️', nameKey: 'sk_c5_armageddon', descKey: 'sk_c5_armageddon_d',
              effects: { damagePct: 0.12, critChancePct: 0.04 } },
            { id: 'c5_ice_age', category: 'combat', tier: 5, x: 2180, y: 960,
              prereq: [], prereqAny: ['c4_magma','c4_blizzard'], excl: ['c5_armageddon'],
              icon: '🧊', nameKey: 'sk_c5_ice_age', descKey: 'sk_c5_ice_age_d',
              effects: { projSpeedPct: 0.10, fireRatePct: -0.05 } },

            // --- MORE COMBAT TIER 1-2 BRANCHES ---
            { id: 'c1_dash', category: 'combat', tier: 1, x: 1980, y: 185,
              prereq: ['c_root'], prereqAny: [], excl: [],
              icon: '💨', nameKey: 'sk_c1_dash', descKey: 'sk_c1_dash_d',
              effects: { damagePct: 0.01, projSpeedPct: 0.01 } },
            { id: 'c2_phantom', category: 'combat', tier: 2, x: 1700, y: 320,
              prereq: ['c1_dash'], prereqAny: [], excl: ['c2_berserker'],
              icon: '👻', nameKey: 'sk_c2_phantom', descKey: 'sk_c2_phantom_d',
              effects: { projSpeedPct: 0.03, critChancePct: 0.01 } },
            { id: 'c2_berserker', category: 'combat', tier: 2, x: 1780, y: 320,
              prereq: ['c1_dash'], prereqAny: [], excl: ['c2_phantom'],
              icon: '😡', nameKey: 'sk_c2_berserker', descKey: 'sk_c2_berserker_d',
              effects: { damagePct: 0.04, fireRatePct: -0.02 } },
            { id: 'c3_shadow_step', category: 'combat', tier: 3, x: 1460, y: 580,
              prereq: ['c2_phantom'], prereqAny: [], excl: [],
              icon: '🌙', nameKey: 'sk_c3_shadow_step', descKey: 'sk_c3_shadow_step_d',
              effects: { critChancePct: 0.03, projSpeedPct: 0.02 } },
            { id: 'c3_rage_burst', category: 'combat', tier: 3, x: 1540, y: 580,
              prereq: ['c2_berserker'], prereqAny: [], excl: [],
              icon: '💢', nameKey: 'sk_c3_rage_burst', descKey: 'sk_c3_rage_burst_d',
              effects: { damagePct: 0.05, fireRatePct: -0.03 } },
            { id: 'c4_phantom_blade', category: 'combat', tier: 4, x: 2100, y: 800,
              prereq: ['c3_shadow_step'], prereqAny: [], excl: [],
              icon: '⚔️', nameKey: 'sk_c4_phantom_blade', descKey: 'sk_c4_phantom_blade_d',
              effects: { critChancePct: 0.04, damagePct: 0.04 } },
            { id: 'c4_wrath', category: 'combat', tier: 4, x: 2180, y: 800,
              prereq: ['c3_rage_burst'], prereqAny: [], excl: [],
              icon: '😤', nameKey: 'sk_c4_wrath', descKey: 'sk_c4_wrath_d',
              effects: { damagePct: 0.09, fireRatePct: -0.02 } },
            { id: 'c5_phantom_lord', category: 'combat', tier: 5, x: 2260, y: 960,
              prereq: ['c4_phantom_blade'], prereqAny: [], excl: [],
              icon: '👑', nameKey: 'sk_c5_phantom_lord', descKey: 'sk_c5_phantom_lord_d',
              effects: { critChancePct: 0.07, critDamagePct: 0.15, damagePct: 0.05 } },
            { id: 'c5_berserker_king', category: 'combat', tier: 5, x: 2340, y: 960,
              prereq: ['c4_wrath'], prereqAny: [], excl: [],
              icon: '🔱', nameKey: 'sk_c5_berserker_king', descKey: 'sk_c5_berserker_king_d',
              effects: { damagePct: 0.12, fireRatePct: -0.04 } },

            // --- COMBAT EXTRA TIER 2-3 NODES ---
            { id: 'c2_precision', category: 'combat', tier: 2, x: 1860, y: 320,
              prereq: ['c2_blade'], prereqAny: [], excl: [],
              icon: '🔭', nameKey: 'sk_c2_precision', descKey: 'sk_c2_precision_d',
              effects: { projRangePct: 0.05, critChancePct: 0.01 } },
            { id: 'c2_accelerator', category: 'combat', tier: 2, x: 1940, y: 320,
              prereq: ['c2_flow'], prereqAny: [], excl: [],
              icon: '🚀', nameKey: 'sk_c2_accelerator', descKey: 'sk_c2_accelerator_d',
              effects: { projSpeedPct: 0.06, fireRatePct: -0.02 } },
            { id: 'c3_eagle_eye', category: 'combat', tier: 3, x: 1620, y: 580,
              prereq: ['c2_precision'], prereqAny: [], excl: [],
              icon: '🦅', nameKey: 'sk_c3_eagle_eye', descKey: 'sk_c3_eagle_eye_d',
              effects: { critChancePct: 0.04, projRangePct: 0.06 } },
            { id: 'c3_jet_stream', category: 'combat', tier: 3, x: 1700, y: 580,
              prereq: ['c2_accelerator'], prereqAny: [], excl: [],
              icon: '💨', nameKey: 'sk_c3_jet_stream', descKey: 'sk_c3_jet_stream_d',
              effects: { projSpeedPct: 0.07, fireRatePct: -0.02 } },
            { id: 'c4_true_aim', category: 'combat', tier: 4, x: 2260, y: 800,
              prereq: ['c3_eagle_eye'], prereqAny: [], excl: [],
              icon: '🎯', nameKey: 'sk_c4_true_aim', descKey: 'sk_c4_true_aim_d',
              effects: { critChancePct: 0.05, damagePct: 0.04 } },
            { id: 'c4_light_speed', category: 'combat', tier: 4, x: 2340, y: 800,
              prereq: ['c3_jet_stream'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_c4_light_speed', descKey: 'sk_c4_light_speed_d',
              effects: { projSpeedPct: 0.10, fireRatePct: -0.03 } },
            { id: 'c5_true_sight', category: 'combat', tier: 5, x: 2420, y: 960,
              prereq: ['c4_true_aim'], prereqAny: [], excl: [],
              icon: '🌠', nameKey: 'sk_c5_true_sight', descKey: 'sk_c5_true_sight_d',
              effects: { critChancePct: 0.08, critDamagePct: 0.18 } },
            { id: 'c5_lightbolt', category: 'combat', tier: 5, x: 2500, y: 960,
              prereq: ['c4_light_speed'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_c5_lightbolt', descKey: 'sk_c5_lightbolt_d',
              effects: { projSpeedPct: 0.12, fireRatePct: -0.04 } },

            // --- ADDITIONAL COMBAT NODES (to reach ~125) ---
            { id: 'cx_soul_blade', category: 'combat', tier: 3, x: 1780, y: 580,
              prereq: ['c2_arcane'], prereqAny: [], excl: [],
              icon: '🌀', nameKey: 'sk_cx_soul_blade', descKey: 'sk_cx_soul_blade_d',
              effects: { damagePct: 0.03, critChancePct: 0.02 } },
            { id: 'cx_death_mark', category: 'combat', tier: 4, x: 2420, y: 800,
              prereq: ['cx_soul_blade'], prereqAny: [], excl: [],
              icon: '💀', nameKey: 'sk_cx_death_mark', descKey: 'sk_cx_death_mark_d',
              effects: { critDamagePct: 0.12, damagePct: 0.04 } },
            { id: 'cx_reaper', category: 'combat', tier: 5, x: 1460, y: 1060,
              prereq: ['cx_death_mark'], prereqAny: [], excl: [],
              icon: '☠️', nameKey: 'sk_cx_reaper', descKey: 'sk_cx_reaper_d',
              effects: { critChancePct: 0.05, critDamagePct: 0.20, damagePct: 0.05 } },
            { id: 'cx_storm_eye', category: 'combat', tier: 3, x: 1860, y: 580,
              prereq: ['c2_burst'], prereqAny: [], excl: [],
              icon: '🌩️', nameKey: 'sk_cx_storm_eye', descKey: 'sk_cx_storm_eye_d',
              effects: { fireRatePct: -0.03, projSpeedPct: 0.03 } },
            { id: 'cx_voltaic', category: 'combat', tier: 4, x: 2500, y: 800,
              prereq: ['cx_storm_eye'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_cx_voltaic', descKey: 'sk_cx_voltaic_d',
              effects: { fireRatePct: -0.04, damagePct: 0.04 } },
            { id: 'cx_thunder_god', category: 'combat', tier: 5, x: 1540, y: 1060,
              prereq: ['cx_voltaic'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_cx_thunder_god', descKey: 'sk_cx_thunder_god_d',
              effects: { fireRatePct: -0.06, damagePct: 0.08, projSpeedPct: 0.05 } },
            { id: 'cx_arcane_surge', category: 'combat', tier: 2, x: 2020, y: 320,
              prereq: ['c1_power'], prereqAny: [], excl: [],
              icon: '🔮', nameKey: 'sk_cx_arcane_surge', descKey: 'sk_cx_arcane_surge_d',
              effects: { damagePct: 0.03, manaCostPct: -0.04 } },
            { id: 'cx_arcane_nova', category: 'combat', tier: 3, x: 1940, y: 580,
              prereq: ['cx_arcane_surge'], prereqAny: [], excl: [],
              icon: '💠', nameKey: 'sk_cx_arcane_nova', descKey: 'sk_cx_arcane_nova_d',
              effects: { damagePct: 0.05, critChancePct: 0.02 } },
            { id: 'cx_arcane_lord', category: 'combat', tier: 4, x: 1540, y: 900,
              prereq: ['cx_arcane_nova'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_cx_arcane_lord', descKey: 'sk_cx_arcane_lord_d',
              effects: { damagePct: 0.07, critDamagePct: 0.10 } },
            { id: 'cx_arcane_ascendant', category: 'combat', tier: 5, x: 1620, y: 1060,
              prereq: ['cx_arcane_lord'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_cx_arcane_ascendant', descKey: 'sk_cx_arcane_ascendant_d',
              effects: { damagePct: 0.10, critChancePct: 0.05, manaCostPct: -0.08 } },
            { id: 'cx_burst_nova', category: 'combat', tier: 2, x: 2100, y: 320,
              prereq: ['c1_speed'], prereqAny: [], excl: [],
              icon: '💫', nameKey: 'sk_cx_burst_nova', descKey: 'sk_cx_burst_nova_d',
              effects: { fireRatePct: -0.03, projSpeedPct: 0.02 } },
            { id: 'cx_chain_reaction', category: 'combat', tier: 3, x: 2020, y: 580,
              prereq: ['cx_burst_nova'], prereqAny: [], excl: [],
              icon: '🔗', nameKey: 'sk_cx_chain_reaction', descKey: 'sk_cx_chain_reaction_d',
              effects: { fireRatePct: -0.04, damagePct: 0.03 } },
            { id: 'cx_cascade', category: 'combat', tier: 4, x: 1620, y: 900,
              prereq: ['cx_chain_reaction'], prereqAny: [], excl: [],
              icon: '🌊', nameKey: 'sk_cx_cascade', descKey: 'sk_cx_cascade_d',
              effects: { fireRatePct: -0.05, damagePct: 0.05 } },
            { id: 'cx_avalanche', category: 'combat', tier: 5, x: 1700, y: 1060,
              prereq: ['cx_cascade'], prereqAny: [], excl: [],
              icon: '❄️', nameKey: 'sk_cx_avalanche', descKey: 'sk_cx_avalanche_d',
              effects: { fireRatePct: -0.07, damagePct: 0.08, projSpeedPct: 0.05 } },
            { id: 'cx_twin_shot', category: 'combat', tier: 2, x: 2180, y: 320,
              prereq: ['c1_power'], prereqAny: [], excl: [],
              icon: '🎯', nameKey: 'sk_cx_twin_shot', descKey: 'sk_cx_twin_shot_d',
              effects: { damagePct: 0.02, projSpeedPct: 0.03 } },
            { id: 'cx_triple_tap', category: 'combat', tier: 3, x: 2100, y: 580,
              prereq: ['cx_twin_shot'], prereqAny: [], excl: [],
              icon: '🔫', nameKey: 'sk_cx_triple_tap', descKey: 'sk_cx_triple_tap_d',
              effects: { damagePct: 0.04, fireRatePct: -0.02 } },
            { id: 'cx_overdrive', category: 'combat', tier: 4, x: 1700, y: 900,
              prereq: ['cx_triple_tap'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_cx_overdrive', descKey: 'sk_cx_overdrive_d',
              effects: { damagePct: 0.06, fireRatePct: -0.04 } },
            { id: 'cx_apex', category: 'combat', tier: 5, x: 1780, y: 1060,
              prereq: ['cx_overdrive'], prereqAny: [], excl: [],
              icon: '🔱', nameKey: 'sk_cx_apex', descKey: 'sk_cx_apex_d',
              effects: { damagePct: 0.10, fireRatePct: -0.05, critChancePct: 0.03 } },

            // ══════════════════════════════════════════
            //  PASSIVE TREE – EXTENDED
            // ══════════════════════════════════════════

            // --- PASSIVE BRANCH: Extended HP/Defense ---
            { id: 'px_tough_skin', category: 'passive', tier: 2, x: 1620, y: 320,
              prereq: ['p1_vitality'], prereqAny: [], excl: [],
              icon: '🛡️', nameKey: 'sk_px_tough_skin', descKey: 'sk_px_tough_skin_d',
              effects: { maxHpFlat: 8, dmgReductionPct: 0.01 } },
            { id: 'px_iron_wall', category: 'passive', tier: 3, x: 1940, y: 480,
              prereq: ['px_tough_skin'], prereqAny: [], excl: [],
              icon: '🏰', nameKey: 'sk_px_iron_wall', descKey: 'sk_px_iron_wall_d',
              effects: { maxHpFlat: 12, dmgReductionPct: 0.02 } },
            { id: 'px_fortress', category: 'passive', tier: 4, x: 1300, y: 800,
              prereq: ['px_iron_wall'], prereqAny: [], excl: [],
              icon: '⚓', nameKey: 'sk_px_fortress', descKey: 'sk_px_fortress_d',
              effects: { maxHpFlat: 18, dmgReductionPct: 0.03 } },
            { id: 'px_colossus', category: 'passive', tier: 5, x: 1620, y: 960,
              prereq: ['px_fortress'], prereqAny: [], excl: [],
              icon: '🗿', nameKey: 'sk_px_colossus', descKey: 'sk_px_colossus_d',
              effects: { maxHpFlat: 25, dmgReductionPct: 0.05, hpRegenPerSec: 0.3 } },
            { id: 'px_regenerator', category: 'passive', tier: 2, x: 1700, y: 320,
              prereq: ['p1_regen'], prereqAny: [], excl: [],
              icon: '🌿', nameKey: 'sk_px_regenerator', descKey: 'sk_px_regenerator_d',
              effects: { hpRegenPerSec: 0.3, maxHpFlat: 5 } },
            { id: 'px_life_spring', category: 'passive', tier: 3, x: 2020, y: 480,
              prereq: ['px_regenerator'], prereqAny: [], excl: [],
              icon: '💧', nameKey: 'sk_px_life_spring', descKey: 'sk_px_life_spring_d',
              effects: { hpRegenPerSec: 0.5, maxHpFlat: 8 } },
            { id: 'px_eternal_youth', category: 'passive', tier: 4, x: 1380, y: 800,
              prereq: ['px_life_spring'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_px_eternal_youth', descKey: 'sk_px_eternal_youth_d',
              effects: { hpRegenPerSec: 0.8, maxHpFlat: 12 } },
            { id: 'px_undying', category: 'passive', tier: 5, x: 1700, y: 960,
              prereq: ['px_eternal_youth'], prereqAny: [], excl: [],
              icon: '♾️', nameKey: 'sk_px_undying', descKey: 'sk_px_undying_d',
              effects: { hpRegenPerSec: 1.2, maxHpFlat: 20, dmgReductionPct: 0.02 } },

            // --- PASSIVE BRANCH: Mana Mastery extended ---
            { id: 'px_mana_well', category: 'passive', tier: 2, x: 1780, y: 320,
              prereq: ['p1_mana'], prereqAny: [], excl: [],
              icon: '🔵', nameKey: 'sk_px_mana_well', descKey: 'sk_px_mana_well_d',
              effects: { maxManaFlat: 12, manaRegenPct: 0.05 } },
            { id: 'px_deep_mana', category: 'passive', tier: 3, x: 2100, y: 480,
              prereq: ['px_mana_well'], prereqAny: [], excl: [],
              icon: '🌊', nameKey: 'sk_px_deep_mana', descKey: 'sk_px_deep_mana_d',
              effects: { maxManaFlat: 18, manaRegenPct: 0.08 } },
            { id: 'px_mana_lord', category: 'passive', tier: 4, x: 1460, y: 800,
              prereq: ['px_deep_mana'], prereqAny: [], excl: [],
              icon: '💎', nameKey: 'sk_px_mana_lord', descKey: 'sk_px_mana_lord_d',
              effects: { maxManaFlat: 25, manaRegenPct: 0.10 } },
            { id: 'px_arcane_ocean', category: 'passive', tier: 5, x: 1780, y: 960,
              prereq: ['px_mana_lord'], prereqAny: [], excl: [],
              icon: '🌌', nameKey: 'sk_px_arcane_ocean', descKey: 'sk_px_arcane_ocean_d',
              effects: { maxManaFlat: 35, manaRegenPct: 0.15, manaCostPct: -0.08 } },

            // --- PASSIVE BRANCH: Speed / Mobility extended ---
            { id: 'px_swift_steps', category: 'passive', tier: 2, x: 1860, y: 320,
              prereq: ['p1_swiftness'], prereqAny: [], excl: [],
              icon: '👟', nameKey: 'sk_px_swift_steps', descKey: 'sk_px_swift_steps_d',
              effects: { speedPct: 0.04 } },
            { id: 'px_wind_runner', category: 'passive', tier: 3, x: 2180, y: 480,
              prereq: ['px_swift_steps'], prereqAny: [], excl: [],
              icon: '💨', nameKey: 'sk_px_wind_runner', descKey: 'sk_px_wind_runner_d',
              effects: { speedPct: 0.06 } },
            { id: 'px_gale_force', category: 'passive', tier: 4, x: 1540, y: 800,
              prereq: ['px_wind_runner'], prereqAny: [], excl: [],
              icon: '🌪️', nameKey: 'sk_px_gale_force', descKey: 'sk_px_gale_force_d',
              effects: { speedPct: 0.08, critChancePct: 0.01 } },
            { id: 'px_sonic_dash', category: 'passive', tier: 5, x: 1860, y: 960,
              prereq: ['px_gale_force'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_px_sonic_dash', descKey: 'sk_px_sonic_dash_d',
              effects: { speedPct: 0.10, damagePct: 0.03 } },

            // --- PASSIVE BRANCH: Gold / Economy extended ---
            { id: 'px_gold_finder', category: 'passive', tier: 2, x: 1940, y: 320,
              prereq: ['p1_fortune'], prereqAny: [], excl: [],
              icon: '🪙', nameKey: 'sk_px_gold_finder', descKey: 'sk_px_gold_finder_d',
              effects: { goldPct: 0.06, luckPct: 0.01 } },
            { id: 'px_treasure_hunter', category: 'passive', tier: 3, x: 2260, y: 480,
              prereq: ['px_gold_finder'], prereqAny: [], excl: [],
              icon: '🗺️', nameKey: 'sk_px_treasure_hunter', descKey: 'sk_px_treasure_hunter_d',
              effects: { goldPct: 0.08, luckPct: 0.02 } },
            { id: 'px_golden_touch', category: 'passive', tier: 4, x: 1620, y: 800,
              prereq: ['px_treasure_hunter'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_px_golden_touch', descKey: 'sk_px_golden_touch_d',
              effects: { goldPct: 0.12, luckPct: 0.03 } },
            { id: 'px_midas', category: 'passive', tier: 5, x: 1940, y: 960,
              prereq: ['px_golden_touch'], prereqAny: [], excl: [],
              icon: '👑', nameKey: 'sk_px_midas', descKey: 'sk_px_midas_d',
              effects: { goldPct: 0.18, luckPct: 0.05, shopSlotsBonus: 1 } },

            // --- PASSIVE BRANCH: Luck / Item Quality extended ---
            { id: 'px_fortune_seeker', category: 'passive', tier: 2, x: 2020, y: 320,
              prereq: ['p1_luck'], prereqAny: [], excl: [],
              icon: '🍀', nameKey: 'sk_px_fortune_seeker', descKey: 'sk_px_fortune_seeker_d',
              effects: { luckPct: 0.04 } },
            { id: 'px_fate_weaver', category: 'passive', tier: 3, x: 2340, y: 480,
              prereq: ['px_fortune_seeker'], prereqAny: [], excl: [],
              icon: '🧵', nameKey: 'sk_px_fate_weaver', descKey: 'sk_px_fate_weaver_d',
              effects: { luckPct: 0.06, goldPct: 0.03 } },
            { id: 'px_destiny_caller', category: 'passive', tier: 4, x: 1700, y: 800,
              prereq: ['px_fate_weaver'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_px_destiny_caller', descKey: 'sk_px_destiny_caller_d',
              effects: { luckPct: 0.08, critChancePct: 0.02 } },
            { id: 'px_fate_master', category: 'passive', tier: 5, x: 2020, y: 960,
              prereq: ['px_destiny_caller'], prereqAny: [], excl: [],
              icon: '🎲', nameKey: 'sk_px_fate_master', descKey: 'sk_px_fate_master_d',
              effects: { luckPct: 0.12, goldPct: 0.08, critChancePct: 0.03 } },

            // --- PASSIVE BRANCH: Damage reduction / shields ---
            { id: 'px_barrier', category: 'passive', tier: 2, x: 2100, y: 320,
              prereq: ['p1_defense'], prereqAny: [], excl: [],
              icon: '🔰', nameKey: 'sk_px_barrier', descKey: 'sk_px_barrier_d',
              effects: { dmgReductionPct: 0.02, maxHpFlat: 6 } },
            { id: 'px_aegis', category: 'passive', tier: 3, x: 2420, y: 480,
              prereq: ['px_barrier'], prereqAny: [], excl: [],
              icon: '🛡️', nameKey: 'sk_px_aegis', descKey: 'sk_px_aegis_d',
              effects: { dmgReductionPct: 0.03, maxHpFlat: 10 } },
            { id: 'px_bulwark_lord', category: 'passive', tier: 4, x: 1780, y: 800,
              prereq: ['px_aegis'], prereqAny: [], excl: [],
              icon: '⚜️', nameKey: 'sk_px_bulwark_lord', descKey: 'sk_px_bulwark_lord_d',
              effects: { dmgReductionPct: 0.04, maxHpFlat: 15, hpRegenPerSec: 0.2 } },
            { id: 'px_divine_shield', category: 'passive', tier: 5, x: 2100, y: 960,
              prereq: ['px_bulwark_lord'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_px_divine_shield', descKey: 'sk_px_divine_shield_d',
              effects: { dmgReductionPct: 0.06, maxHpFlat: 20, hpRegenPerSec: 0.4 } },

            // --- PASSIVE BRANCH: Utility/Runes extended ---
            { id: 'px_rune_scholar', category: 'passive', tier: 2, x: 2180, y: 320,
              prereq: ['p1_collector'], prereqAny: [], excl: [],
              icon: '📚', nameKey: 'sk_px_rune_scholar', descKey: 'sk_px_rune_scholar_d',
              effects: { luckPct: 0.02, goldPct: 0.03 } },
            { id: 'px_rune_master', category: 'passive', tier: 3, x: 2500, y: 480,
              prereq: ['px_rune_scholar'], prereqAny: [], excl: [],
              icon: '🔮', nameKey: 'sk_px_rune_master', descKey: 'sk_px_rune_master_d',
              effects: { luckPct: 0.04, goldPct: 0.04 } },
            { id: 'px_rune_sovereign', category: 'passive', tier: 4, x: 1860, y: 800,
              prereq: ['px_rune_master'], prereqAny: [], excl: [],
              icon: '👑', nameKey: 'sk_px_rune_sovereign', descKey: 'sk_px_rune_sovereign_d',
              effects: { luckPct: 0.06, goldPct: 0.06 } },
            { id: 'px_rune_god', category: 'passive', tier: 5, x: 2180, y: 960,
              prereq: ['px_rune_sovereign'], prereqAny: [], excl: [],
              icon: '🌌', nameKey: 'sk_px_rune_god', descKey: 'sk_px_rune_god_d',
              effects: { luckPct: 0.10, goldPct: 0.10, shopSlotsBonus: 1 } },

            // --- PASSIVE EXTRA BRANCHES (intermediate nodes) ---
            { id: 'px_combat_exp', category: 'passive', tier: 3, x: 1300, y: 580,
              prereq: ['p1_swiftness'], prereqAny: [], excl: [],
              icon: '⚔️', nameKey: 'sk_px_combat_exp', descKey: 'sk_px_combat_exp_d',
              effects: { damagePct: 0.02, speedPct: 0.02 } },
            { id: 'px_veteran', category: 'passive', tier: 4, x: 1940, y: 800,
              prereq: ['px_combat_exp'], prereqAny: [], excl: [],
              icon: '🏅', nameKey: 'sk_px_veteran', descKey: 'sk_px_veteran_d',
              effects: { damagePct: 0.04, maxHpFlat: 8 } },
            { id: 'px_warlord', category: 'passive', tier: 5, x: 2260, y: 960,
              prereq: ['px_veteran'], prereqAny: [], excl: [],
              icon: '⚔️', nameKey: 'sk_px_warlord', descKey: 'sk_px_warlord_d',
              effects: { damagePct: 0.07, maxHpFlat: 15, speedPct: 0.03 } },
            { id: 'px_potion_master', category: 'passive', tier: 3, x: 1380, y: 580,
              prereq: ['p2_sustain'], prereqAny: [], excl: [],
              icon: '🧪', nameKey: 'sk_px_potion_master', descKey: 'sk_px_potion_master_d',
              effects: { startPotionsFlat: 1, hpRegenPerSec: 0.2 } },
            { id: 'px_alchemist', category: 'passive', tier: 4, x: 2020, y: 800,
              prereq: ['px_potion_master'], prereqAny: [], excl: [],
              icon: '⚗️', nameKey: 'sk_px_alchemist', descKey: 'sk_px_alchemist_d',
              effects: { startPotionsFlat: 1, maxHpFlat: 10 } },
            { id: 'px_grand_alchemist', category: 'passive', tier: 5, x: 2340, y: 960,
              prereq: ['px_alchemist'], prereqAny: [], excl: [],
              icon: '🌿', nameKey: 'sk_px_grand_alchemist', descKey: 'sk_px_grand_alchemist_d',
              effects: { startPotionsFlat: 2, maxHpFlat: 20, hpRegenPerSec: 0.5 } },
            { id: 'px_sly_merchant', category: 'passive', tier: 3, x: 1460, y: 580,
              prereq: ['p2_commerce'], prereqAny: [], excl: [],
              icon: '🤝', nameKey: 'sk_px_sly_merchant', descKey: 'sk_px_sly_merchant_d',
              effects: { goldPct: 0.05, luckPct: 0.02 } },
            { id: 'px_trade_baron', category: 'passive', tier: 4, x: 2100, y: 800,
              prereq: ['px_sly_merchant'], prereqAny: [], excl: [],
              icon: '💼', nameKey: 'sk_px_trade_baron', descKey: 'sk_px_trade_baron_d',
              effects: { goldPct: 0.08, shopSlotsBonus: 1 } },
            { id: 'px_magnate', category: 'passive', tier: 5, x: 2420, y: 960,
              prereq: ['px_trade_baron'], prereqAny: [], excl: [],
              icon: '🏦', nameKey: 'sk_px_magnate', descKey: 'sk_px_magnate_d',
              effects: { goldPct: 0.14, luckPct: 0.05, shopSlotsBonus: 1 } },
            { id: 'px_arcane_blood', category: 'passive', tier: 3, x: 1540, y: 580,
              prereq: ['p2_survivability'], prereqAny: [], excl: [],
              icon: '🩸', nameKey: 'sk_px_arcane_blood', descKey: 'sk_px_arcane_blood_d',
              effects: { maxHpFlat: 10, damagePct: 0.02 } },
            { id: 'px_blood_knight', category: 'passive', tier: 4, x: 2180, y: 800,
              prereq: ['px_arcane_blood'], prereqAny: [], excl: [],
              icon: '🗡️', nameKey: 'sk_px_blood_knight', descKey: 'sk_px_blood_knight_d',
              effects: { maxHpFlat: 15, damagePct: 0.04, hpRegenPerSec: 0.2 } },
            { id: 'px_death_knight', category: 'passive', tier: 5, x: 2500, y: 960,
              prereq: ['px_blood_knight'], prereqAny: [], excl: [],
              icon: '💀', nameKey: 'sk_px_death_knight', descKey: 'sk_px_death_knight_d',
              effects: { maxHpFlat: 22, damagePct: 0.07, dmgReductionPct: 0.03 } },
            { id: 'px_sage', category: 'passive', tier: 3, x: 1620, y: 580,
              prereq: ['p2_wisdom'], prereqAny: [], excl: [],
              icon: '📖', nameKey: 'sk_px_sage', descKey: 'sk_px_sage_d',
              effects: { maxManaFlat: 10, manaRegenPct: 0.06 } },
            { id: 'px_archmage', category: 'passive', tier: 4, x: 2260, y: 800,
              prereq: ['px_sage'], prereqAny: [], excl: [],
              icon: '🧙', nameKey: 'sk_px_archmage', descKey: 'sk_px_archmage_d',
              effects: { maxManaFlat: 18, manaRegenPct: 0.10, manaCostPct: -0.05 } },
            { id: 'px_elder_mage', category: 'passive', tier: 5, x: 1460, y: 1060,
              prereq: ['px_archmage'], prereqAny: [], excl: [],
              icon: '🌠', nameKey: 'sk_px_elder_mage', descKey: 'sk_px_elder_mage_d',
              effects: { maxManaFlat: 30, manaRegenPct: 0.15, manaCostPct: -0.10 } },
            { id: 'px_scout', category: 'passive', tier: 2, x: 2260, y: 320,
              prereq: ['p1_vitality'], prereqAny: [], excl: [],
              icon: '🔍', nameKey: 'sk_px_scout', descKey: 'sk_px_scout_d',
              effects: { speedPct: 0.03, luckPct: 0.01 } },
            { id: 'px_ranger', category: 'passive', tier: 3, x: 1700, y: 580,
              prereq: ['px_scout'], prereqAny: [], excl: [],
              icon: '🏕️', nameKey: 'sk_px_ranger', descKey: 'sk_px_ranger_d',
              effects: { speedPct: 0.04, goldPct: 0.03 } },
            { id: 'px_pathfinder', category: 'passive', tier: 4, x: 2340, y: 800,
              prereq: ['px_ranger'], prereqAny: [], excl: [],
              icon: '🧭', nameKey: 'sk_px_pathfinder', descKey: 'sk_px_pathfinder_d',
              effects: { speedPct: 0.05, luckPct: 0.03, goldPct: 0.03 } },
            { id: 'px_explorer', category: 'passive', tier: 5, x: 1540, y: 1060,
              prereq: ['px_pathfinder'], prereqAny: [], excl: [],
              icon: '🗺️', nameKey: 'sk_px_explorer', descKey: 'sk_px_explorer_d',
              effects: { speedPct: 0.07, luckPct: 0.05, goldPct: 0.05 } },
            { id: 'px_runic_bond', category: 'passive', tier: 2, x: 2340, y: 320,
              prereq: ['p1_luck'], prereqAny: [], excl: [],
              icon: '🔗', nameKey: 'sk_px_runic_bond', descKey: 'sk_px_runic_bond_d',
              effects: { luckPct: 0.03, maxManaFlat: 5 } },
            { id: 'px_runic_affinity', category: 'passive', tier: 3, x: 1780, y: 580,
              prereq: ['px_runic_bond'], prereqAny: [], excl: [],
              icon: '🌀', nameKey: 'sk_px_runic_affinity', descKey: 'sk_px_runic_affinity_d',
              effects: { luckPct: 0.05, manaCostPct: -0.04 } },
            { id: 'px_runic_mastery', category: 'passive', tier: 4, x: 2420, y: 800,
              prereq: ['px_runic_affinity'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_px_runic_mastery', descKey: 'sk_px_runic_mastery_d',
              effects: { luckPct: 0.07, manaCostPct: -0.06, damagePct: 0.02 } },
            { id: 'px_runic_transcendence', category: 'passive', tier: 5, x: 1620, y: 1060,
              prereq: ['px_runic_mastery'], prereqAny: [], excl: [],
              icon: '🌌', nameKey: 'sk_px_runic_transcendence', descKey: 'sk_px_runic_transcendence_d',
              effects: { luckPct: 0.10, manaCostPct: -0.10, damagePct: 0.05 } },

            // ══════════════════════════════════════════
            //  COMBAT TREE – FINAL BRANCHES (to reach 125)
            // ══════════════════════════════════════════
            { id: 'ca_war_cry', category: 'combat', tier: 2, x: 2260, y: 320,
              prereq: ['c1_speed'], prereqAny: [], excl: [],
              icon: '📣', nameKey: 'sk_ca_war_cry', descKey: 'sk_ca_war_cry_d',
              effects: { damagePct: 0.02, fireRatePct: -0.01 } },
            { id: 'ca_frenzy', category: 'combat', tier: 3, x: 2180, y: 580,
              prereq: ['ca_war_cry'], prereqAny: [], excl: [],
              icon: '🔥', nameKey: 'sk_ca_frenzy', descKey: 'sk_ca_frenzy_d',
              effects: { damagePct: 0.03, fireRatePct: -0.02 } },
            { id: 'ca_berserk', category: 'combat', tier: 4, x: 1780, y: 900,
              prereq: ['ca_frenzy'], prereqAny: [], excl: [],
              icon: '😤', nameKey: 'sk_ca_berserk', descKey: 'sk_ca_berserk_d',
              effects: { damagePct: 0.05, fireRatePct: -0.03 } },
            { id: 'ca_godmode', category: 'combat', tier: 5, x: 1860, y: 1060,
              prereq: ['ca_berserk'], prereqAny: [], excl: [],
              icon: '🔱', nameKey: 'sk_ca_godmode', descKey: 'sk_ca_godmode_d',
              effects: { damagePct: 0.08, fireRatePct: -0.04, critChancePct: 0.03 } },
            { id: 'ca_mana_surge', category: 'combat', tier: 2, x: 2340, y: 320,
              prereq: ['c2_fire'], prereqAny: [], excl: [],
              icon: '🌊', nameKey: 'sk_ca_mana_surge', descKey: 'sk_ca_mana_surge_d',
              effects: { damagePct: 0.02, manaCostPct: -0.03 } },
            { id: 'ca_spell_weave', category: 'combat', tier: 3, x: 2260, y: 580,
              prereq: ['ca_mana_surge'], prereqAny: [], excl: [],
              icon: '🕸️', nameKey: 'sk_ca_spell_weave', descKey: 'sk_ca_spell_weave_d',
              effects: { damagePct: 0.04, manaCostPct: -0.05 } },
            { id: 'ca_arcane_weave', category: 'combat', tier: 4, x: 1860, y: 900,
              prereq: ['ca_spell_weave'], prereqAny: [], excl: [],
              icon: '🔮', nameKey: 'sk_ca_arcane_weave', descKey: 'sk_ca_arcane_weave_d',
              effects: { damagePct: 0.06, critChancePct: 0.02 } },
            { id: 'ca_grand_weave', category: 'combat', tier: 5, x: 1940, y: 1060,
              prereq: ['ca_arcane_weave'], prereqAny: [], excl: [],
              icon: '🌌', nameKey: 'sk_ca_grand_weave', descKey: 'sk_ca_grand_weave_d',
              effects: { damagePct: 0.10, critDamagePct: 0.12, manaCostPct: -0.08 } },
            { id: 'ca_quickdraw', category: 'combat', tier: 2, x: 2420, y: 320,
              prereq: ['c2_flow'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_ca_quickdraw', descKey: 'sk_ca_quickdraw_d',
              effects: { fireRatePct: -0.02, projSpeedPct: 0.02 } },
            { id: 'ca_snap_shot', category: 'combat', tier: 3, x: 2340, y: 580,
              prereq: ['ca_quickdraw'], prereqAny: [], excl: [],
              icon: '📸', nameKey: 'sk_ca_snap_shot', descKey: 'sk_ca_snap_shot_d',
              effects: { fireRatePct: -0.03, critChancePct: 0.02 } },
            { id: 'ca_flash_cast', category: 'combat', tier: 4, x: 1940, y: 900,
              prereq: ['ca_snap_shot'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_ca_flash_cast', descKey: 'sk_ca_flash_cast_d',
              effects: { fireRatePct: -0.04, projSpeedPct: 0.05 } },
            { id: 'ca_speed_demon', category: 'combat', tier: 5, x: 2020, y: 1060,
              prereq: ['ca_flash_cast'], prereqAny: [], excl: [],
              icon: '😈', nameKey: 'sk_ca_speed_demon', descKey: 'sk_ca_speed_demon_d',
              effects: { fireRatePct: -0.06, projSpeedPct: 0.07, damagePct: 0.03 } },
            { id: 'ca_elemental_mastery', category: 'combat', tier: 3, x: 2420, y: 580,
              prereq: ['c2_fire'], prereqAny: [], excl: [],
              icon: '🌍', nameKey: 'sk_ca_elemental_mastery', descKey: 'sk_ca_elemental_mastery_d',
              effects: { damagePct: 0.04, critChancePct: 0.01 } },
            { id: 'ca_prime_element', category: 'combat', tier: 4, x: 2020, y: 900,
              prereq: ['ca_elemental_mastery'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_ca_prime_element', descKey: 'sk_ca_prime_element_d',
              effects: { damagePct: 0.06, critDamagePct: 0.08 } },
            { id: 'ca_worldbreaker', category: 'combat', tier: 5, x: 2100, y: 1060,
              prereq: ['ca_prime_element'], prereqAny: [], excl: [],
              icon: '💥', nameKey: 'sk_ca_worldbreaker', descKey: 'sk_ca_worldbreaker_d',
              effects: { damagePct: 0.12, critChancePct: 0.04, projSpeedPct: 0.04 } },
            { id: 'ca_mana_cannon', category: 'combat', tier: 3, x: 2500, y: 580,
              prereq: ['cx_arcane_surge'], prereqAny: [], excl: [],
              icon: '💣', nameKey: 'sk_ca_mana_cannon', descKey: 'sk_ca_mana_cannon_d',
              effects: { damagePct: 0.05, projSpeedPct: 0.03 } },
            { id: 'ca_arcane_bomb', category: 'combat', tier: 4, x: 2100, y: 900,
              prereq: ['ca_mana_cannon'], prereqAny: [], excl: [],
              icon: '💥', nameKey: 'sk_ca_arcane_bomb', descKey: 'sk_ca_arcane_bomb_d',
              effects: { damagePct: 0.07, projRangePct: 0.05 } },
            { id: 'ca_nova_lord', category: 'combat', tier: 5, x: 2180, y: 1060,
              prereq: ['ca_arcane_bomb'], prereqAny: [], excl: [],
              icon: '🌠', nameKey: 'sk_ca_nova_lord', descKey: 'sk_ca_nova_lord_d',
              effects: { damagePct: 0.11, projSpeedPct: 0.06, critChancePct: 0.03 } },
            { id: 'ca_void_touched', category: 'combat', tier: 3, x: 1860, y: 680,
              prereq: ['c3_shadow_step'], prereqAny: [], excl: [],
              icon: '🌑', nameKey: 'sk_ca_void_touched', descKey: 'sk_ca_void_touched_d',
              effects: { damagePct: 0.04, critChancePct: 0.02 } },
            { id: 'ca_void_walker', category: 'combat', tier: 4, x: 2180, y: 900,
              prereq: ['ca_void_touched'], prereqAny: [], excl: [],
              icon: '👁️', nameKey: 'sk_ca_void_walker', descKey: 'sk_ca_void_walker_d',
              effects: { damagePct: 0.06, critDamagePct: 0.10 } },
            { id: 'ca_void_ascendant', category: 'combat', tier: 5, x: 2260, y: 1060,
              prereq: ['ca_void_walker'], prereqAny: [], excl: [],
              icon: '🌌', nameKey: 'sk_ca_void_ascendant', descKey: 'sk_ca_void_ascendant_d',
              effects: { damagePct: 0.10, critChancePct: 0.06, critDamagePct: 0.15 } },
            { id: 'ca_rage_nova', category: 'combat', tier: 3, x: 1940, y: 680,
              prereq: ['c3_rage_burst'], prereqAny: [], excl: [],
              icon: '💢', nameKey: 'sk_ca_rage_nova', descKey: 'sk_ca_rage_nova_d',
              effects: { damagePct: 0.04, fireRatePct: -0.02 } },
            { id: 'ca_berserker_rage', category: 'combat', tier: 4, x: 2260, y: 900,
              prereq: ['ca_rage_nova'], prereqAny: [], excl: [],
              icon: '🔥', nameKey: 'sk_ca_berserker_rage', descKey: 'sk_ca_berserker_rage_d',
              effects: { damagePct: 0.06, fireRatePct: -0.03 } },
            { id: 'ca_ultimate_rage', category: 'combat', tier: 5, x: 2340, y: 1060,
              prereq: ['ca_berserker_rage'], prereqAny: [], excl: [],
              icon: '💀', nameKey: 'sk_ca_ultimate_rage', descKey: 'sk_ca_ultimate_rage_d',
              effects: { damagePct: 0.12, fireRatePct: -0.05, critChancePct: 0.04 } },

            // ══════════════════════════════════════════
            //  PASSIVE TREE – FINAL BRANCHES (to reach 125)
            // ══════════════════════════════════════════
            { id: 'pa_wanderer', category: 'passive', tier: 2, x: 2420, y: 320,
              prereq: ['p1_swiftness'], prereqAny: [], excl: [],
              icon: '🧳', nameKey: 'sk_pa_wanderer', descKey: 'sk_pa_wanderer_d',
              effects: { speedPct: 0.03, luckPct: 0.02 } },
            { id: 'pa_drifter', category: 'passive', tier: 3, x: 1860, y: 580,
              prereq: ['pa_wanderer'], prereqAny: [], excl: [],
              icon: '🌬️', nameKey: 'sk_pa_drifter', descKey: 'sk_pa_drifter_d',
              effects: { speedPct: 0.05, goldPct: 0.03 } },
            { id: 'pa_nomad', category: 'passive', tier: 4, x: 2500, y: 800,
              prereq: ['pa_drifter'], prereqAny: [], excl: [],
              icon: '🗺️', nameKey: 'sk_pa_nomad', descKey: 'sk_pa_nomad_d',
              effects: { speedPct: 0.07, luckPct: 0.04 } },
            { id: 'pa_free_spirit', category: 'passive', tier: 5, x: 1700, y: 1060,
              prereq: ['pa_nomad'], prereqAny: [], excl: [],
              icon: '🦋', nameKey: 'sk_pa_free_spirit', descKey: 'sk_pa_free_spirit_d',
              effects: { speedPct: 0.10, luckPct: 0.06, goldPct: 0.05 } },
            { id: 'pa_spell_saver', category: 'passive', tier: 2, x: 2500, y: 320,
              prereq: ['p1_mana'], prereqAny: [], excl: [],
              icon: '💰', nameKey: 'sk_pa_spell_saver', descKey: 'sk_pa_spell_saver_d',
              effects: { manaCostPct: -0.04, maxManaFlat: 6 } },
            { id: 'pa_efficient_caster', category: 'passive', tier: 3, x: 1940, y: 580,
              prereq: ['pa_spell_saver'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_pa_efficient_caster', descKey: 'sk_pa_efficient_caster_d',
              effects: { manaCostPct: -0.06, manaRegenPct: 0.05 } },
            { id: 'pa_mana_efficient', category: 'passive', tier: 4, x: 1620, y: 900,
              prereq: ['pa_efficient_caster'], prereqAny: [], excl: [],
              icon: '🔋', nameKey: 'sk_pa_mana_efficient', descKey: 'sk_pa_mana_efficient_d',
              effects: { manaCostPct: -0.08, maxManaFlat: 12 } },
            { id: 'pa_zero_cost', category: 'passive', tier: 5, x: 1780, y: 1060,
              prereq: ['pa_mana_efficient'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_pa_zero_cost', descKey: 'sk_pa_zero_cost_d',
              effects: { manaCostPct: -0.12, maxManaFlat: 20, manaRegenPct: 0.08 } },
            { id: 'pa_survivor', category: 'passive', tier: 2, x: 1660, y: 420,
              prereq: ['p1_regen'], prereqAny: [], excl: [],
              icon: '🏥', nameKey: 'sk_pa_survivor', descKey: 'sk_pa_survivor_d',
              effects: { hpRegenPerSec: 0.2, maxHpFlat: 6 } },
            { id: 'pa_endure', category: 'passive', tier: 3, x: 2020, y: 580,
              prereq: ['pa_survivor'], prereqAny: [], excl: [],
              icon: '💪', nameKey: 'sk_pa_endure', descKey: 'sk_pa_endure_d',
              effects: { hpRegenPerSec: 0.3, dmgReductionPct: 0.01 } },
            { id: 'pa_resilient', category: 'passive', tier: 4, x: 1700, y: 900,
              prereq: ['pa_endure'], prereqAny: [], excl: [],
              icon: '🛡️', nameKey: 'sk_pa_resilient', descKey: 'sk_pa_resilient_d',
              effects: { hpRegenPerSec: 0.5, dmgReductionPct: 0.02, maxHpFlat: 8 } },
            { id: 'pa_unkillable', category: 'passive', tier: 5, x: 1860, y: 1060,
              prereq: ['pa_resilient'], prereqAny: [], excl: [],
              icon: '♾️', nameKey: 'sk_pa_unkillable', descKey: 'sk_pa_unkillable_d',
              effects: { hpRegenPerSec: 0.8, dmgReductionPct: 0.04, maxHpFlat: 18 } },
            { id: 'pa_hoarder', category: 'passive', tier: 2, x: 1740, y: 420,
              prereq: ['p1_fortune'], prereqAny: [], excl: [],
              icon: '🧺', nameKey: 'sk_pa_hoarder', descKey: 'sk_pa_hoarder_d',
              effects: { goldPct: 0.04, luckPct: 0.02 } },
            { id: 'pa_collector2', category: 'passive', tier: 3, x: 2100, y: 580,
              prereq: ['pa_hoarder'], prereqAny: [], excl: [],
              icon: '🏛️', nameKey: 'sk_pa_collector2', descKey: 'sk_pa_collector2_d',
              effects: { goldPct: 0.06, luckPct: 0.03 } },
            { id: 'pa_vault', category: 'passive', tier: 4, x: 1780, y: 900,
              prereq: ['pa_collector2'], prereqAny: [], excl: [],
              icon: '🏦', nameKey: 'sk_pa_vault', descKey: 'sk_pa_vault_d',
              effects: { goldPct: 0.10, luckPct: 0.04, shopSlotsBonus: 1 } },
            { id: 'pa_emperor', category: 'passive', tier: 5, x: 1940, y: 1060,
              prereq: ['pa_vault'], prereqAny: [], excl: [],
              icon: '👑', nameKey: 'sk_pa_emperor', descKey: 'sk_pa_emperor_d',
              effects: { goldPct: 0.16, luckPct: 0.07, shopSlotsBonus: 1 } },
            { id: 'pa_mystic', category: 'passive', tier: 2, x: 1820, y: 420,
              prereq: ['p1_luck'], prereqAny: [], excl: [],
              icon: '🔮', nameKey: 'sk_pa_mystic', descKey: 'sk_pa_mystic_d',
              effects: { luckPct: 0.03, damagePct: 0.01 } },
            { id: 'pa_oracle', category: 'passive', tier: 3, x: 2180, y: 580,
              prereq: ['pa_mystic'], prereqAny: [], excl: [],
              icon: '👁️', nameKey: 'sk_pa_oracle', descKey: 'sk_pa_oracle_d',
              effects: { luckPct: 0.05, critChancePct: 0.02 } },
            { id: 'pa_seer', category: 'passive', tier: 4, x: 1860, y: 900,
              prereq: ['pa_oracle'], prereqAny: [], excl: [],
              icon: '🌙', nameKey: 'sk_pa_seer', descKey: 'sk_pa_seer_d',
              effects: { luckPct: 0.07, critChancePct: 0.03, goldPct: 0.04 } },
            { id: 'pa_prophet', category: 'passive', tier: 5, x: 2020, y: 1060,
              prereq: ['pa_seer'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_pa_prophet', descKey: 'sk_pa_prophet_d',
              effects: { luckPct: 0.11, critChancePct: 0.05, goldPct: 0.06 } },
            { id: 'pa_shield_bash', category: 'passive', tier: 2, x: 1900, y: 420,
              prereq: ['p1_defense'], prereqAny: [], excl: [],
              icon: '🛡️', nameKey: 'sk_pa_shield_bash', descKey: 'sk_pa_shield_bash_d',
              effects: { dmgReductionPct: 0.01, maxHpFlat: 5 } },
            { id: 'pa_phalanx', category: 'passive', tier: 3, x: 2260, y: 580,
              prereq: ['pa_shield_bash'], prereqAny: [], excl: [],
              icon: '⚜️', nameKey: 'sk_pa_phalanx', descKey: 'sk_pa_phalanx_d',
              effects: { dmgReductionPct: 0.02, maxHpFlat: 8 } },
            { id: 'pa_sentinel', category: 'passive', tier: 4, x: 1940, y: 900,
              prereq: ['pa_phalanx'], prereqAny: [], excl: [],
              icon: '🏰', nameKey: 'sk_pa_sentinel', descKey: 'sk_pa_sentinel_d',
              effects: { dmgReductionPct: 0.03, maxHpFlat: 12, hpRegenPerSec: 0.2 } },
            { id: 'pa_titan', category: 'passive', tier: 5, x: 2100, y: 1060,
              prereq: ['pa_sentinel'], prereqAny: [], excl: [],
              icon: '🗿', nameKey: 'sk_pa_titan', descKey: 'sk_pa_titan_d',
              effects: { dmgReductionPct: 0.05, maxHpFlat: 22, hpRegenPerSec: 0.4 } },

            // --- FINAL COMBAT NODES (reach 125) ---
            { id: 'cf_overload', category: 'combat', tier: 2, x: 2500, y: 320,
              prereq: ['c2_blade'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_cf_overload', descKey: 'sk_cf_overload_d',
              effects: { damagePct: 0.03 } },
            { id: 'cf_cascade_fire', category: 'combat', tier: 2, x: 1900, y: 420,
              prereq: ['c2_flow'], prereqAny: [], excl: [],
              icon: '🌊', nameKey: 'sk_cf_cascade_fire', descKey: 'sk_cf_cascade_fire_d',
              effects: { fireRatePct: -0.02, projSpeedPct: 0.02 } },

            // --- FINAL PASSIVE NODES (reach 125) ---
            { id: 'pf_power_surge', category: 'passive', tier: 2, x: 1980, y: 420,
              prereq: ['p1_regen'], prereqAny: [], excl: [],
              icon: '⚡', nameKey: 'sk_pf_power_surge', descKey: 'sk_pf_power_surge_d',
              effects: { maxHpFlat: 6, damagePct: 0.01 } },
            { id: 'pf_endurance', category: 'passive', tier: 2, x: 2060, y: 420,
              prereq: ['p1_defense'], prereqAny: [], excl: [],
              icon: '💪', nameKey: 'sk_pf_endurance', descKey: 'sk_pf_endurance_d',
              effects: { dmgReductionPct: 0.01, maxHpFlat: 4 } },
            { id: 'pf_gold_rush', category: 'passive', tier: 2, x: 2140, y: 420,
              prereq: ['p1_fortune'], prereqAny: [], excl: [],
              icon: '🏃', nameKey: 'sk_pf_gold_rush', descKey: 'sk_pf_gold_rush_d',
              effects: { goldPct: 0.04 } },
            { id: 'pf_second_wind', category: 'passive', tier: 3, x: 2340, y: 580,
              prereq: ['pf_power_surge'], prereqAny: [], excl: [],
              icon: '🌬️', nameKey: 'sk_pf_second_wind', descKey: 'sk_pf_second_wind_d',
              effects: { hpRegenPerSec: 0.3, maxHpFlat: 8 } },
            { id: 'pf_stalwart', category: 'passive', tier: 3, x: 2420, y: 580,
              prereq: ['pf_endurance'], prereqAny: [], excl: [],
              icon: '🏋️', nameKey: 'sk_pf_stalwart', descKey: 'sk_pf_stalwart_d',
              effects: { dmgReductionPct: 0.02, maxHpFlat: 10 } },
            { id: 'pf_prospector', category: 'passive', tier: 3, x: 2500, y: 580,
              prereq: ['pf_gold_rush'], prereqAny: [], excl: [],
              icon: '⛏️', nameKey: 'sk_pf_prospector', descKey: 'sk_pf_prospector_d',
              effects: { goldPct: 0.06, luckPct: 0.02 } },
            { id: 'pf_last_stand', category: 'passive', tier: 4, x: 2020, y: 900,
              prereq: ['pf_second_wind'], prereqAny: [], excl: [],
              icon: '⚔️', nameKey: 'sk_pf_last_stand', descKey: 'sk_pf_last_stand_d',
              effects: { maxHpFlat: 14, dmgReductionPct: 0.02 } },
            { id: 'pf_guardian_spirit', category: 'passive', tier: 4, x: 2100, y: 900,
              prereq: ['pf_stalwart'], prereqAny: [], excl: [],
              icon: '👼', nameKey: 'sk_pf_guardian_spirit', descKey: 'sk_pf_guardian_spirit_d',
              effects: { dmgReductionPct: 0.03, hpRegenPerSec: 0.25 } },
            { id: 'pf_gold_empire', category: 'passive', tier: 4, x: 2180, y: 900,
              prereq: ['pf_prospector'], prereqAny: [], excl: [],
              icon: '🏛️', nameKey: 'sk_pf_gold_empire', descKey: 'sk_pf_gold_empire_d',
              effects: { goldPct: 0.10, luckPct: 0.04 } },
            { id: 'pf_transcendent', category: 'passive', tier: 5, x: 2180, y: 1060,
              prereq: ['pf_last_stand'], prereqAny: [], excl: [],
              icon: '✨', nameKey: 'sk_pf_transcendent', descKey: 'sk_pf_transcendent_d',
              effects: { maxHpFlat: 20, dmgReductionPct: 0.04, hpRegenPerSec: 0.5 } },
            { id: 'pf_divine', category: 'passive', tier: 5, x: 2260, y: 1060,
              prereq: ['pf_guardian_spirit'], prereqAny: [], excl: [],
              icon: '🌟', nameKey: 'sk_pf_divine', descKey: 'sk_pf_divine_d',
              effects: { dmgReductionPct: 0.05, maxHpFlat: 18, hpRegenPerSec: 0.6 } },
            { id: 'pf_golden_age', category: 'passive', tier: 5, x: 2340, y: 1060,
              prereq: ['pf_gold_empire'], prereqAny: [], excl: [],
              icon: '👑', nameKey: 'sk_pf_golden_age', descKey: 'sk_pf_golden_age_d',
              effects: { goldPct: 0.16, luckPct: 0.07, shopSlotsBonus: 1 } },

        ], // end nodes array

        // Helper: node by id
        getNode(id) {
            return this.nodes.find(n => n.id === id) || null;
        },
        // Nodes by category
        byCategory(cat) {
            return this.nodes.filter(n => n.category === cat);
        },
        // Cost for a node
        getCost(node) {
            return this.tierCosts[node.tier] || 2;
        },
    };

    window.SkillTreeData = SkillTreeData;
})();
